package lu.even.manual_timing.events;

public enum EventAction {
  REFRESH_INSCRIPTIONS,
  REFRESH_TIMES,
  GET,
  POST,
  LOGIN,
  PUT,
  USER_MOVE,
  GET_BY_LANE,
  GET_ALL,
  GET_BY_EVENT_LANE,
  REPLACE_TIMES,
  GET_BY_EVENT_HEAT,
  LOAD_EVENTS,
  REPLACE_EVENTS,
  LOAD_HEAT,
  REPLACE_INSCRIPTIONS,
  DUMP,
  LOAD,
  SAVE_TIME;
}
