package lu.even.manual_timing.events;

public enum EventAction {
    REFRESH_INSCRIPTIONS, REFRESH_TIMES, GET, POST, LOGIN, PUT, USER_MOVE, GET_BY_LANE, GET_ALL, GET_BY_EVENT_LANE, GET_BY_EVENT_HEAT, POOL_CONFIG_CHANGED
}
